---
# defaults file for cdh.common
configured_dependencies: []
common_packages:
  - acl
  - build-essential
  - curl
  - git
  - unzip
  - zip
  - python-pip
  - python-setuptools
  - libssl-dev
  - wget
  - tmux
  - python-virtualenv