###
# Toggle between two most recent deploys (if two exist) of a project,
# allowing for a quick reversion to a previous iteration.
#
# Example usage:
# ansible-playbook -e host_group=prosody_qa revert_deployment.yml
#
# The script will ask for confirmation before making any breaking changes.
# ctrl+c and then 'a 'will break execution, enter or ctrl+c and then 'c' will
# proceed.
#
# NOTE: You will need the password file loaded for any secrets encrypted in
# the vaults used by the host_group specified..
###

- hosts: '{{ host_group }}'
  connection: ssh
  remote_user: deploy
  environment:
    PATH: '{{ path }}'
    LD_LIBRARY_PATH: '{{ ld_library_path }}'
    PYTHONPATH: '{{ python_path }}'
  tasks:
  - name: Pause and let user make sure command looks right.
    pause:
      prompt: >
               You are about to revert {{ host_group | upper }}.
               Press enter to proceed or ctrl+c then a to abort.
  - name: Check that previous symlink exists.
    stat:
      path: "{{ install_root }}/previous"
    register: previous
  - fail:
      msg: "Previous symlink does not exist."
    when: previous.stat.islnk is not defined
  - name: Get current symlink path
    stat:
      path: "{{ install_root }}/current"
    register: current
  - fail:
      msg: "Current symlink does not exist."
    when: current.stat.islnk is not defined
  - name: Set active symlink to previous.
    file:
      src: "{{ previous.stat.lnk_source }}"
      dest: "/var/www/{{ symlink }}"
      state: link
  - name: Set previous to current
    file:
      src: "{{ current.stat.lnk_source }}"
      dest: "{{ install_root }}/previous"
      state: link
  - name: Set current to reflect actual symlink
    file:
      src: "{{ previous.stat.lnk_source }}"
      dest: "{{ install_root }}/current"
      state: link
  - name: Restart httpd24
    command: "sudo systemctl restart httpd24-httpd"
    args:
      warn: false