- hosts: winthrop_staging
  connection: ssh
  remote_user: deploy
  # Set environment to use scl rh-python35 in group_vars
  environment:
    PATH: '{{ path }}'
    LD_LIBRARY_PATH: '{{ ld_library_path }}'
    PYTHONPATH: '{{ python_path }}'
  roles:
    - prep_staging
    - build_project_repo
    - build_virtualenv
    - build_npm
    - install_local_settings
    - django_collectstatic
    - django_compressor
    - backup_database
    - django_migrate
    - finalize_deploy
    - restart_httpd
