---
# tasks file for cdh.common
- name: install common packages
  apt:
    name: '{{ common_packages }}'
    state: present
    update_cache: true
  changed_when: false

- name: copy tmux.conf
  template:
    src: "tmux.conf.j2"
    dest: "/etc/tmux.conf"