###
# Prepare vhost and wsgi configurations for staging VM.  This inserts a
# correctly templated configuration for the Virtualhost and wsgi.
###
---

# This task runs on the host machine, because git stores files as 644 or 755
# and host keys need to be 600, even if we're using a deliberately insecure
# key for a test box as in this case.
- name: Set permissions on id_rsa after any git changes
  local_action:
    module: file
    path: vagrant/id_rsa
    mode: 0600
  become: false
- name: Create vhost configuration
  template:
    src: '{{ templates_dir }}/staging_vagrant/apache_vhost.conf'
    dest: /etc/httpd/conf.d/apache_vhost.conf
- name: Create directory for wsgi settings
  file:
    state: directory
    dest: /etc/httpd/conf.d/staging
    owner: root
    group: root
- name: Create wsgi configuration
  template:
    src: '{{ templates_dir }}/staging_vagrant/apache_wsgi.conf'
    dest: /etc/httpd/conf.d/staging/wsgi.conf
- name: Clear /var/www/ and /srv/www
  shell: 'rm -rf /var/www/* && rm -rf /srv/www/*'
  args:
    executable: /bin/bash
    warn: false
- name: Remove staging db if exists
  mysql_db:
    name: staging
    state: absent
- name: Create staging db
  mysql_db:
    name: staging
    state: present
