##
# Get the repo's Solr configset synced with PUL's infrastructure.
##

## DOCUMENTATION
# https://lucene.apache.org/solr/guide/8_1/using-zookeeper-to-manage-configuration-files.html

## TODO
# - define solr_url

- name: Update and configure Solr configset
  block:
    - name: Copy project Solr configset files for upload to zookeeper
        # synchronize configset from deploy
        - synchronize:
            mode: pull
            src: "{{ deploy }}/solr_conf"
            dest: "/solr/cdh_solr/cdh_{{ app_name }}_solr_conf"
        delegate_to: solr_cloud

    - name: Update configset with zookeeper
        command: "solr zk -upconfig -d /solr/cdh_solr/cdh_{{ app_name }}_solr_conf -n {{ solr_collection }} -z {{ zk_host }}"
        args:
            chdir: /opt/solr/bin
        delegate_to: solr_cloud

    - name: Get a list of current Solr collections
      uri:
        url: "{{ solr_url }}/admin/collections?action=LIST"
      register: solr_collections_list

    - name: Create Solr collection if it doesn't already exist
      uri:
        url: "{{ solr_url }}/admin/collections?action=CREATE&name={{ solr_collection }}&collection.configName={{ solr_collection }}"  # other opts
        when:  "{{ solr_collection }} not in {{ solr_collections_list.collections }}"

    - name: Reload the collection if not newly created
        uri:
          url: "{{ solr_url }}/admin/collections?action=RELOAD&name={{ solr_collection }}"
        when:  "{{ solr_collection }} in {{ solr_collections_list.collections }}"

    - name: Apply any managed schema changes by running django solr_schema
      django_manage:
        command: "solr_schema --no-input"
        app_path: "{{ deploy }}"
        virtualenv: "{{ deploy }}/env"
        when:  "{{ solr_collection }} not in {{ solr_collections_list.collections }}"

  rescue:
      - include_tasks: roles/create_deployment/tasks/fail.yml
