- hosts: geniza_qa
  connection: ssh
  remote_user: pulsys
  vars_files:
    - ./group_vars/geniza_qa_i18n/vars.yml
    - ./group_vars/geniza_qa_i18n/vault.yml
  roles:
    # - create_deployment
    - deploy_user
    - build_project_repo
    - build_virtualenv
    - postgresql
    - configure_apache
    - install_local_settings
    - django_collectstatic
    - django_migrate
    - finalize_deploy
    # - close_deployment
